import image from "../assets/image.png";
export const goodsSale = [
  {
    id: "1",
    status: "sale",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
  {
    id: "2",
    status: "sale",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
  {
    id: "3",
    status: "sale",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
  {
    id: "4",
    status: "sale",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
  {
    id: "5",
    status: "sale",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
];
export const goodsNew = [
  {
    id: "1",
    status: "new",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
  {
    id: "2",
    status: "new",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
  {
    id: "3",
    status: "new",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
  {
    id: "4",
    status: "new",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
  {
    id: "5",
    status: "new",
    category: "Аксессуары для бани",
    categoryMain: "Товары для ванны и бани",
    title: "Дверка прочистная ДПР (150х112)",
    reviews: 4.8,
    isCount: true,
    price: 1361,
    image: image,
  },
];
